# Generated by Django 4.0.6 on 2022-07-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_author_email_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='caption',
        ),
        migrations.AddField(
            model_name='tag',
            name='caption',
            field=models.ManyToManyField(to='blog.post'),
        ),
    ]
